version: "3.8"

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - packages/lqrk-core/common.env
    volumes:
      - lqrk-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  user:
    extends:
      file: services/user.yml
      service: user
    env_file:
      - packages/lqrk-core/common.env
    depends_on:
      - postgres
  liquor:
    extends:
      file: services/liquor.yml
      service: liquor
    env_file:
      - packages/lqrk-core/common.env
    depends_on:
      - postgres
  client:
    extends:
      file: services/client.yml
      service: client
    env_file:
      - packages/lqrk-core/common.env

volumes:
  lqrk-data: