require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1.0
  TargetRailsVersion: 7.0
  Exclude:
    - 'db/**/*'
    - 'spec/**/*' # linting rspec stuff adds over 1k non-auto-correctable warnings

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/**/*'
    - 'config/**/*'

# Rubocop tends to complain about lack of documentation on Rails' own classes
Style/Documentation:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging