version: '3.8'
services:
  user:
    build: ../../user_service
    command: ["sh", "/app/start.sh"]
    volumes:
      - ../../user_service:/app
    ports:
      - "8881:8881"
    depends_on:
      - postgres